#coding:utf-8
from selenium import webdriver
import os
import re
import datetime
import unittest
import HTMLTestRunner
from config.selenium_config import selenium_config
from public.common.sendEmail import send_email_report
from config.email_config import email_config

#webdriver浏览器设置
def set_driver(browser):
    if str(browser).lower() not in ('chrome', 'firefox'):
        return False
    elif str(browser).lower() == 'chrome':
        selenium_config['browser'] = 'chrome'
        selenium_config['driver'] = webdriver.Chrome()
    elif str(browser).lower() == 'firefox':
        selenium_config['browser'] = 'firefox'
        selenium_config['driver'] = webdriver.Firefox()
    selenium_config['driver'].implicitly_wait(10)

#报告路径和快照目录配置
def set_path(browser, project):
    # 设置快照和报告路径
    date_str = re.sub('[- :]', '', str(datetime.datetime.now()).split('.')[0])
    selenium_config['snapshot_path'] = os.getcwd() + '\\snapshot\\' + str(project).upper() + '\\' + str(browser).upper() + '\\' + str(browser).upper() + date_str
    selenium_config['report_file_path'] = os.getcwd() + '\\report\\' + str(project).upper() + '_' + str(browser).upper() + '_' + 'HTMLReport' + date_str + '.html'

def selenium_common(browser, project):

    set_driver(browser)
    set_path(browser, project)

    from public.selenium_test.CRM.CRM_Process import CRM_Process

    # 设置测试用例组件
    suite = unittest.TestSuite()

    # 用例流程添加
    tests = [CRM_Process("test_open_url"),
             #CRM_Process("test_login"),
             #CRM_Process("test_power_manager"),
             CRM_Process("test_login"),
             CRM_Process("test_account_manager"),
             CRM_Process("test_driver_close")
             ]
    suite.addTests(tests)


    with open(selenium_config['report_file_path'], 'w') as report_f:
        runner = HTMLTestRunner.HTMLTestRunner(
            stream=report_f,
            title=project + '_' + browser + '_' + '自动化测试报告',
            description='generated by HTMLTestRunner.',
            verbosity=2
        )
        runner.run(suite)

    #邮件发送
    email_config['receiver'] = 'liuxu@guxiansheng.cn'
    email_config['attachment'] = [selenium_config['report_file_path']]
    email_config['mail_body'] = 'CRM系统自动化测试报告邮件内容'
    send_email_report(email_config)
